basicPath: /api/v1

apiPath:
  - /user/login
  - /user/register

typeFile: types/example.go

logic:
  file: logic/logic.go
  receiver: "*UserLogic"

handler:
  file: handler/handler.go

router:
  file: router/router.go
  groupFunc: UserRouter
