apiPath:
  - /login
  - /register

typeFile: example/types/example.go

logic:
  file: example/logic/logic.go
  receiver: "*UserLogic"

handler:
  file: example/handler/handler.go

router:
  file: example/router/router.go
  groupFunc: UserRouter
